rem OMEGA_GO.exe

rem OMEGA_ETAT_LIQUIDITES.exe

rem OMEGA_ASSISTANT_TRESO.exe

GO_PROCESS "C:\FGA_SOFT\DEVELOPPEMENT\PROJET\FGA_Soft_Integration\BATCH\AUTOIT\OMEGA_DETAIL_FIFO.exe"

rem OMEGA_VALORISATION_POSITION_TAUX.exe

rem OMEGA_VALORISATION_POSITION_ACTION.exe