OMEGA_GO.exe

OMEGA_ETAT_LIQUIDITES.exe

OMEGA_ASSISTANT_TRESO.exe

rem GO_PROCESS "C:\FGA_SOFT\DEVELOPPEMENT\PROJET\FGA_Soft_Integration\BATCH\AUTOIT\OMEGA_DETAIL_FIFO.exe"

OMEGA_VALORISATION_POSITION_TAUX.exe

OMEGA_VALORISATION_POSITION_ACTION.exe