"C:\Program Files (x86)\7-Zip\7z" e "G:\,FGA Systèmes\PRODUCTION\FTP\BNPP\NAV_FILES\*.NAV_FILES_*.zip" -o"G:\,FGA Systèmes\PRODUCTION\FTP\BNPP\NAV_FILES\Unzip"

move "G:\,FGA Systèmes\PRODUCTION\FTP\BNPP\NAV_FILES\*.NAV_FILES_*.zip" "G:\,FGA Systèmes\PRODUCTION\FTP\BNPP\NAV_FILES\Archive\"
move "G:\,FGA Systèmes\PRODUCTION\FTP\BNPP\NAV_FILES\Unzip\*FONDS*.*" "G:\,FGA Systèmes\SCD\IMPLEMENTATION\5 - TRANSACTIONS RAPPRO\BP2S\pack VL\"
move "G:\,FGA Systèmes\PRODUCTION\FTP\BNPP\NAV_FILES\Unzip\POSI*.*" "G:\,FGA Systèmes\SCD\IMPLEMENTATION\5 - TRANSACTIONS RAPPRO\BP2S\POSI\"
move "G:\,FGA Systèmes\PRODUCTION\FTP\BNPP\NAV_FILES\Unzip\CSTA*.*" "G:\,FGA Systèmes\SCD\IMPLEMENTATION\5 - TRANSACTIONS RAPPRO\BP2S\CSTA\"


